services:

  # etebar-traefik:
  #   container_name: etebar-traefik
  #   image: traefik:latest
  #   command:
  #     - "--log.level=DEBUG"

  #     #Traefik Dashboard
  #     - "--api=true"
  #     - "--api.insecure=true"
  #     - "--providers.docker=true"
  #     - "--providers.docker.network=my-net"
  #     - "--providers.docker.exposedbydefault=false"
      
  #     # Set entryPoints
  #     - "--entryPoints.http.address=:80"
  #     - "--entryPoints.https.address=:443"
  #     - "--entryPoints.https.http.tls=true"
  #     - "--entryPoints.http.forwardedHeaders.insecure=true"
  #     - "--entryPoints.https.forwardedHeaders.insecure=true"

  #     # Enabling SSL & HTTPS
  #     - "--certificatesResolvers.myresolver.acme.httpChallenge=true"
  #     - "--certificatesResolvers.myresolver.acme.httpChallenge.entryPoint=http"
  #     - "--certificatesResolvers.myresolver.acme.email=${EMAIL}"
  #     - "--certificatesResolvers.myresolver.acme.storage=/letsencrypt/acme.json"

  #   # Only expose Traefik ports
  #   ports:
  #     - "80:80"
  #     - "443:443"

  #   dns:
  #     - 8.8.8.8
  #     - 8.8.4.4

  #   restart: unless-stopped
    
  #   volumes:
  #     - /var/run/docker.sock:/var/run/docker.sock:ro
  #     - ./letsencrypt:/letsencrypt

  #   networks:
  #     - my-net

  #   labels:
  #     - "traefik.enable=true"
  #     - "traefik.docker.network=my-net"

  #     # HTTP
  #     - "traefik.http.routers.traefik.rule=Host(`${TRAEFIK_DASHBOARD_ADDRESS}`)"
  #     - "traefik.http.routers.traefik.entrypoints=http"
  #     - "traefik.http.routers.traefik.service=traefik-service"

  #     # HTTPS
  #     - "traefik.http.routers.traefik-secure.rule=Host(`${TRAEFIK_DASHBOARD_ADDRESS}`)"
  #     - "traefik.http.routers.traefik-secure.entrypoints=https"
  #     - "traefik.http.routers.traefik-secure.tls=true"
  #     - "traefik.http.routers.traefik-secure.tls.certresolver=myresolver"
  #     - "traefik.http.routers.traefik-secure.service=traefik-service"

  #     # Redirect HTTP to HTTPS
  #     - "traefik.http.middlewares.http-to-https.redirectScheme.scheme=https"
  #     - "traefik.http.routers.traefik.middlewares=http-to-https"

  #     # Load balancer
  #     - "traefik.http.services.traefik-service.loadbalancer.server.port=8080"

  #     # Auth
  #     - "traefik.http.middlewares.web-auth.basicauth.users=${TRAEFIK_DASHBOARD_USERPASS}"
  #     - "traefik.http.routers.traefik_dashboard-secure.middlewares=web-auth"




  etebar-web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: etebar-web
    restart: unless-stopped

    volumes:
      # - ./db.sqlite3:/app/db.sqlite3
      - static_volume:/app/staticfiles
      - media_volume:/app/media

    ports:
      - "8888:8000"
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=rahsaz-net"

      # HTTP
      - "traefik.http.routers.etebar-web.rule=Host(`etebarinomco.top`)"
      - "traefik.http.routers.etebar-web.entrypoints=http"
      - "traefik.http.routers.etebar-web.service=etebar-web-service"

      # HTTPS
      - "traefik.http.routers.etebar-web-secure.rule=Host(`etebarinomco.top`)"
      - "traefik.http.routers.etebar-web-secure.entrypoints=https"
      - "traefik.http.routers.etebar-web-secure.tls=true"
      - "traefik.http.routers.etebar-web-secure.tls.certresolver=myresolver"
      - "traefik.http.routers.etebar-web-secure.service=etebar-web-service"

      # Redirect HTTP to HTTPS
      - "traefik.http.middlewares.http-to-https.redirectScheme.scheme=https"
      - "traefik.http.routers.etebar-web.middlewares=http-to-https"

      # Load balancer
      - "traefik.http.services.etebar-web-service.loadbalancer.server.port=8000"

    
    # command: >
    #   sh -c "
    #     python manage.py migrate && 


    networks:
      - rahsaz-net

networks:
  rahsaz-net:
    name: rahsaz-net
    external: true

volumes:
  static_volume:
  media_volume: