# Generated by Django 5.2.4 on 2025-07-11 10:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CreditRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_type', models.CharField(choices=[('loan_purchase', 'خرید امتیاز وام'), ('goods_loan', 'وام خرید کالا'), ('direct_credit', 'تخصیص اعتبار خرید کالا')], max_length=20, null=True, verbose_name='نوع درخواست')),
                ('requested_amount', models.BigIntegerField(null=True, verbose_name='مبلغ درخواستی')),
                ('payment_receipt', models.FileField(blank=True, null=True, upload_to='payment_receipts/', verbose_name='فیش پرداخت')),
                ('validation_payment_receipt', models.FileField(blank=True, null=True, upload_to='payment_receipts/', verbose_name='فیش پرداخت اعتبار سنجی')),
                ('subscription_payment_receipt', models.FileField(blank=True, null=True, upload_to='payment_receipts/', verbose_name='فیش پرداخت حق اشتراک')),
                ('full_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='نام و نام خانوادگی')),
                ('father_name', models.CharField(max_length=100, null=True, verbose_name='نام پدر')),
                ('national_id', models.CharField(max_length=10, null=True, verbose_name='کد ملی')),
                ('card_serial', models.CharField(max_length=20, null=True, verbose_name='سریال کارت ملی')),
                ('birth_date', models.DateField(null=True, verbose_name='تاریخ تولد')),
                ('birth_place_province', models.CharField(max_length=50, null=True, verbose_name='استان محل تولد')),
                ('birth_place_city', models.CharField(max_length=50, null=True, verbose_name='شهر محل تولد')),
                ('landline_number', models.CharField(max_length=15, null=True, verbose_name='شماره تلفن ثابت')),
                ('province', models.CharField(max_length=50, null=True, verbose_name='استان محل سکونت')),
                ('city', models.CharField(max_length=50, null=True, verbose_name='شهر محل سکونت')),
                ('area', models.CharField(max_length=100, null=True, verbose_name='منطقه')),
                ('address_line', models.TextField(null=True, verbose_name='خیابان و آدرس دقیق')),
                ('plaque', models.CharField(max_length=10, null=True, verbose_name='پلاک')),
                ('unit', models.CharField(max_length=10, null=True, verbose_name='واحد')),
                ('postal_code', models.CharField(max_length=10, null=True, verbose_name='کد پستی')),
                ('iban', models.CharField(max_length=26, null=True, verbose_name='شماره شبا (بدون IR)')),
                ('account_number', models.CharField(max_length=20, null=True, verbose_name='شماره حساب بانکی')),
                ('applicant_signature', models.ImageField(blank=True, null=True, upload_to='signatures/', verbose_name='امضای متقاضی')),
                ('guarantor_signature', models.ImageField(blank=True, null=True, upload_to='signatures/', verbose_name='امضای ضامن')),
                ('guarantor_full_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='نام و نام خانوادگی ضامن')),
                ('guarantor_national_id', models.CharField(blank=True, max_length=10, null=True, verbose_name='کد ملی ضامن')),
                ('guarantor_card_serial', models.CharField(blank=True, max_length=20, null=True, verbose_name='سریال کارت ملی جدید ضامن')),
                ('guarantor_birth_date', models.DateField(blank=True, null=True, verbose_name='تاریخ تولد ضامن')),
                ('guarantor_phone_number', models.CharField(blank=True, max_length=11, null=True, verbose_name='شماره تماس ضامن')),
                ('guarantor_address', models.TextField(blank=True, null=True, verbose_name='آدرس محل سکونت ضامن')),
                ('guarantor_credit_score', models.IntegerField(blank=True, null=True, verbose_name='رتبه اعتبارسنجی ضامن(به انگلیسی)')),
                ('guarantor_consent', models.BooleanField(default=False, verbose_name='پذیرش قوانین توسط ضامن')),
                ('applicant_id_card_front', models.FileField(blank=True, null=True, upload_to='documents/applicant/', verbose_name='تصویر روی کارت ملی متقاضی')),
                ('applicant_id_card_back', models.FileField(blank=True, null=True, upload_to='documents/applicant/', verbose_name='تصویر پشت کارت ملی متقاضی')),
                ('applicant_birth_certificate', models.FileField(blank=True, null=True, upload_to='documents/applicant/', verbose_name='تصویر شناسنامه متقاضی')),
                ('guarantor_id_card_front', models.FileField(blank=True, null=True, upload_to='documents/guarantor/', verbose_name='تصویر روی کارت ملی ضامن')),
                ('guarantor_id_card_back', models.FileField(blank=True, null=True, upload_to='documents/guarantor/', verbose_name='تصویر پشت کارت ملی ضامن')),
                ('guarantor_birth_certificate', models.FileField(blank=True, null=True, upload_to='documents/guarantor/', verbose_name='تصویر شناسنامه ضامن')),
                ('status', models.CharField(choices=[('step1_draft', 'مرحله ۱: پیش\u200cنویس اطلاعات فردی'), ('step1_submitted', 'مرحله ۱: ارسال شده برای بررسی'), ('step1_rejected', 'مرحله ۱: نیاز به اصلاح اطلاعات'), ('step2_draft', 'مرحله ۲: پیش\u200cنویس اطلاعات ضامن'), ('step2_submitted', 'مرحله ۲: ارسال شده برای بررسی'), ('step2_rejected', 'مرحله ۲: نیاز به اصلاح اطلاعات'), ('step3_draft', 'مرحله ۳: پیش\u200cنویس بارگذاری مدارک'), ('step3_submitted', 'مرحله ۳: ارسال شده برای بررسی'), ('step3_rejected', 'مرحله ۳: نیاز به اصلاح مدارک'), ('step4_draft', 'مرحله ۴: پیش\u200cنویس تایید قوانین'), ('final_submission', 'تایید نهایی، در انتظار بررسی کارشناس'), ('approved', 'تایید نهایی توسط کارشناسی'), ('rejected', 'رد شده'), ('completed', 'تکمیل شده (کد پستی ثبت شد)')], default='step1_draft', max_length=20, verbose_name='وضعیت پرونده')),
                ('rejection_reason', models.TextField(blank=True, null=True, verbose_name='دلیل رد شدن مرحله')),
                ('postal_tracking_code', models.CharField(blank=True, max_length=50, null=True, verbose_name='کد رهگیری پستی')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='آخرین بروزرسانی')),
                ('applicant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='متقاضی')),
            ],
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='عنوان تیکت')),
                ('status', models.CharField(choices=[('open', 'باز'), ('closed', 'بسته شده')], default='open', max_length=10, verbose_name='وضعیت')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tickets', to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
            ],
        ),
        migrations.CreateModel(
            name='TicketMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField(verbose_name='متن پیام')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ارسال')),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='requests.ticket', verbose_name='تیکت')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='ارسال کننده')),
            ],
        ),
    ]
