# Generated by Django 5.2.4 on 2025-07-11 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requests', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='creditrequest',
            name='validation_document',
            field=models.FileField(blank=True, null=True, upload_to='validation_document/', verbose_name='سند اعتبار سنجی'),
        ),
    ]
